### ISSUE TITLE
KeyError: 'person'

### ISSUE THREAD

**Issue by wentianl20** [isabek/XmlToTxt#1]
Traceback (most recent call last):
  File "xmltotxt.py", line 33, in <module>
    main()
  File "xmltotxt.py", line 29, in main
    transformer.transform()
  File "/home/ubuntu/ext/XmlToTxt/transformer.py", line 18, in transform
    self.write_to_txt(annotations, classes)
  File "/home/ubuntu/ext/XmlToTxt/transformer.py", line 23, in write_to_txt
    f.write(self.to_darknet_format(annotation, classes))
  File "/home/ubuntu/ext/XmlToTxt/transformer.py", line 29, in to_darknet_format
    result.append("%d %.6f %.6f %.6f %.6f" % (classes[obj.name], x, y, width, height))
KeyError: 'person'

**Comment by samuvack** [comment]
I have the same problem.

Traceback (most recent call last):
  File "xmltotxt.py", line 33, in <module>
    main()
  File "xmltotxt.py", line 29, in main
    transformer.transform()
  File "/var/calculate/ImageNet_Utils/XmlToTxt/transformer.py", line 18, in transform
    self.write_to_txt(annotations, classes)
  File "/var/calculate/ImageNet_Utils/XmlToTxt/transformer.py", line 23, in write_to_txt
    f.write(self.to_darknet_format(annotation, classes))
  File "/var/calculate/ImageNet_Utils/XmlToTxt/transformer.py", line 29, in to_darknet_format
    result.append("%d %.6f %.6f %.6f %.6f" % (classes[obj.name], x, y, width, height))
KeyError: 'door'


@wentianl20 : Did you find already a solution?

**Comment by samuvack** [comment]
Python raises a KeyError whenever a dict() object is requested (using the format a = adict[key]) and the key is not in the dictionary.

**Comment by isabek** [comment]
@wentianl20, @samuvack sorry for late response. You should add all of your labels to classes.txt file. 

@wentianl20 you should add **person** to classes.txt file (and other labels also).

@samuvack you should add **door** to classes.txt file (and other labels also).

P.S: I have updated repo. Now it prints a clear message when you try to run the script without adding labels to classes.txt.
