### ISSUE TITLE
Conversion Error : ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by NaeemKhan333** [isabek/XmlToTxt#6]
ERROR:root:('Missing required array: "objects"',)
Traceback (most recent call last):
  File "xmltotxt.py", line 33, in <module>
    main()
  File "xmltotxt.py", line 29, in main
    transformer.transform()
  File "/home/MyPc/Downloads/XmlToTxt/transformer.py", line 18, in transform
    self.write_to_txt(annotations, classes)
  File "/home/MyPc/Downloads/XmlToTxt/transformer.py", line 23, in write_to_txt
    f.write(self.to_darknet_format(annotation, classes))
  File "/home/MyPc/Downloads/XmlToTxt/transformer.py", line 31, in to_darknet_format
    x, y, width, height = self.get_object_params(obj, annotation.size)
  File "/home/MyPc/Downloads/XmlToTxt/transformer.py", line 48, in get_object_params
    x = absolute_x / image_width
ZeroDivisionError: float division by zero

Can You Help me About this issue ? Thanks

**Comment by karam-nus** [comment]
Just add a check for size in the write_to_txt function as below 

```
    def write_to_txt(self, annotations, classes):
        for annotation in annotations:
            if(annotation.size.width != 0):
                with open(os.path.join(self.out_dir, self.darknet_filename_format(annotation.filename)), "w+") as f:
                    f.write(self.to_darknet_format(annotation, classes))
            print(annotation.filename," complate")
```

Please make sure that only a few annotations have the size as 0, as all those files will be skipped by above code:
`grep "<width>0</width>" ../2_HD/dataset/Annotations/*`
